/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala3;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author jtetzner
 */
public class mancala extends javax.swing.JFrame {

    public static Pit pits[];
    public static int clicked;
    public boolean start;
    public static boolean anotherMove;
    public static int numToGoal;
    public static int playerNum;
    public static boolean p1Human;
    public static boolean p2Human;
    public static int limit;
    public static String computer1FullPath;
    public static String computer2FullPath;
    public static Player currentPlayer;
    public boolean p1Assigned = false;
    public boolean p2Assigned = false;
    

    /**
     * Creates new form mancala
     */
    public mancala() {

        initComponents();
        updateTimeLimit();
    }

    public JButton[] returnButtonArr()
    {
        JButton[] array = new JButton[14];
        //p1
        array[0] = goal1;
        array[1] = jButton1;
        array[2] = jButton2;
        array[3] = jButton3;
        array[4] = jButton4;
        array[5] = jButton5;
        array[6] = jButton6;
        //p2
        array[7] = goal2;
        array[8] = jButton9;
        array[9] = jButton10;
        array[10] = jButton11;
        array[11] = jButton12;
        array[12] = jButton13;
        array[13] = jButton14;

        return array;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        player1HumanButton = new javax.swing.JButton();
        player1ComputerButton = new javax.swing.JButton();
        player2HumanButton = new javax.swing.JButton();
        player2ComputerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        resetGameButton = new javax.swing.JButton();
        computer1FileName = new javax.swing.JLabel();
        computer2FileName = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        timeLimitInput = new javax.swing.JTextField();
        errorText = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        goal1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        goal2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        debugInfo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1Label.setText("Player 1:");

        player2Label.setText("Player 2:");

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        jLabel3.setText("Mancala");

        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel5.setText("P1 Goal");

        jLabel6.setText("P2 Goal");

        jLayeredPane1.setLayer(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        player1HumanButton.setText("Human");
        player1HumanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1HumanButtonMouseClicked(evt);
            }
        });

        player1ComputerButton.setText("Computer...");
        player1ComputerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player1ComputerButtonMouseClicked(evt);
            }
        });

        player2HumanButton.setText("Human");
        player2HumanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2HumanButtonMouseClicked(evt);
            }
        });

        player2ComputerButton.setText("Computer...");
        player2ComputerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player2ComputerButtonMouseClicked(evt);
            }
        });

        jLabel4.setText("Control");

        startGameButton.setBackground(new java.awt.Color(255, 255, 255));
        startGameButton.setText("Start Game");
        startGameButton.setEnabled(false);
        startGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startGameButtonMouseClicked(evt);
            }
        });

        resetGameButton.setText("Reset Game");
        resetGameButton.setEnabled(false);
        resetGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetGameButtonMouseClicked(evt);
            }
        });

        turnLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        turnLabel.setText("Player 1's Turn");

        jLabel7.setText("AI Time Limit (seconds): ");

        timeLimitInput.setText("5");
        timeLimitInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                timeLimitInputFocusLost(evt);
            }
        });

        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        debugInfo.setColumns(20);
        debugInfo.setRows(5);
        jScrollPane1.setViewportView(debugInfo);

        jLabel8.setText("Debug Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(player1HumanButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(159, 159, 159)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(computer2FileName)
                                                .addComponent(player1ComputerButton)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(player2HumanButton)
                                            .addGap(67, 67, 67)
                                            .addComponent(player2ComputerButton))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(183, 183, 183)
                                    .addComponent(resetGameButton))
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(timeLimitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(startGameButton))
                                .addComponent(jSeparator2))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(computer1FileName))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(goal1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(456, 456, 456)
                                        .addComponent(goal2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(player1Label))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(turnLabel)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1HumanButton)
                            .addComponent(player1ComputerButton)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(player2HumanButton)
                            .addComponent(player2ComputerButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(timeLimitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startGameButton)
                            .addComponent(resetGameButton))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(computer1FileName))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(goal2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goal1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(computer2FileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorText))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        if (gameStarted() && Mancala3.isValid(13, currentPlayer)) {
            clicked = 13;
            moveStones(13);
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (gameStarted() && Mancala3.isValid(1, currentPlayer)) {
            clicked = 1;
            moveStones(1);
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (gameStarted() && Mancala3.isValid(2, currentPlayer)) {
            moveStones(2);
            clicked = 2;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (gameStarted() && Mancala3.isValid(3, currentPlayer)) {
            moveStones(3);
            clicked = 3;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (gameStarted() && Mancala3.isValid(4, currentPlayer)) {
            moveStones(4);
            clicked = 4;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (gameStarted() && Mancala3.isValid(5, currentPlayer)) {
            moveStones(5);
            clicked =5;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        if (gameStarted() && Mancala3.isValid(12, currentPlayer)) {
            moveStones(12);
            clicked = 12;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        if (gameStarted() && Mancala3.isValid(10, currentPlayer)) {
            moveStones(10);
            clicked = 10;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        if (gameStarted() && Mancala3.isValid(11, currentPlayer)) {
            moveStones(11);
            clicked = 11;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if (gameStarted() && Mancala3.isValid(9, currentPlayer)) {
            moveStones(9);
            clicked = 9;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        if (gameStarted() && Mancala3.isValid(8, currentPlayer)) {
            moveStones(8);
            clicked = 8;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (gameStarted() && Mancala3.isValid(6, currentPlayer)) {
            moveStones(6);
            clicked = 6;
            currentPlayer.setMoveMade(true);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void player1HumanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1HumanButtonMouseClicked
        player1Label.setText("Player 1: Human");
        player1HumanButton.setSelected(true);
        player1ComputerButton.setSelected(false);
        addDebug("P1 human");
        p1Human = true;
        p1Assigned = true;

        if (gameCanStart()) {
            startGameButton.setEnabled(true);
        }
    }//GEN-LAST:event_player1HumanButtonMouseClicked

    private void resetGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetGameButtonMouseClicked
        Mancala3.initPits(returnButtonArr());
        player1HumanButton.setSelected(false);
        player1ComputerButton.setSelected(false);
        player2HumanButton.setSelected(false);
        player2ComputerButton.setSelected(false);
        timeLimitInput.setEnabled(true);
        startGameButton.setEnabled(false);
        start = false;
        p1Assigned = false;
        p2Assigned = false;
    }//GEN-LAST:event_resetGameButtonMouseClicked

    private void player1ComputerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player1ComputerButtonMouseClicked
        computer1FullPath = getFile();
        File filename = new File(computer1FullPath);
        player1Label.setText("Player 1: " + filename.getName());

        if (computer1FullPath.equals("")) {
            player1HumanButton.setSelected(true);
            player1ComputerButton.setSelected(false);
        } else {
            player1HumanButton.setSelected(false);
            player1ComputerButton.setSelected(true);
            addDebug("P1 computer");
            p1Human = false;
            p1Assigned = true;
        }

        if (gameCanStart()) {
            startGameButton.setEnabled(true);
        }
    }//GEN-LAST:event_player1ComputerButtonMouseClicked

    private void player2HumanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2HumanButtonMouseClicked
        player2Label.setText("Player 2: Human");
        player2HumanButton.setSelected(true);
        player2ComputerButton.setSelected(false);

        addDebug("P2 human");
        p2Human = true;
        p2Assigned = true;
        
        if (gameCanStart()) {
            startGameButton.setEnabled(true);
        }
    }//GEN-LAST:event_player2HumanButtonMouseClicked

    private void player2ComputerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player2ComputerButtonMouseClicked
        computer2FullPath = getFile();
        File filename = new File(computer2FullPath);
        player2Label.setText("Player 2: " + filename.getName());

        if (computer2FullPath.equals("")) {
            player2HumanButton.setSelected(true);
            player2ComputerButton.setSelected(false);
        } else {
            player2HumanButton.setSelected(false);
            player2ComputerButton.setSelected(true);
            addDebug("P2 computer");
            p2Human = false;
            p2Assigned = true;
        }

        if (gameCanStart()) {
            startGameButton.setEnabled(true);
        }
    }//GEN-LAST:event_player2ComputerButtonMouseClicked

    private void startGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGameButtonMouseClicked
        resetGameButton.setEnabled(true);
        timeLimitInput.setEnabled(false);
        start = true;
    }//GEN-LAST:event_startGameButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void timeLimitInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timeLimitInputFocusLost
        updateTimeLimit();
    }

    public void updateTimeLimit() {
        int number=0;
        try{
            number = Integer.parseInt(timeLimitInput.getText());
            errorText.setText("");
        }catch (NumberFormatException ex) {
            errorText.setText("Please enter an integer for the time limit");
        }
        limit = number;
    }//GEN-LAST:event_timeLimitInputFocusLost


    public boolean gameCanStart()
    {
        boolean canStart = p1Assigned
                && p2Assigned
                && (errorText.getText().equals(""));
        return canStart;
    }
    
    public boolean gameStarted() {
        return start;
    }

    public String getFile()
    {
        // create an object of JFileChooser class
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        j.addChoosableFileFilter(new FileNameExtensionFilter("JAR files", "jar"));
        j.setAcceptAllFileFilterUsed(false);

        // invoke the showsOpenDialog function to show the save dialog
        int r = j.showOpenDialog(null);

        // if the user selects a file
        if (r == JFileChooser.APPROVE_OPTION)
        {
            // set the label to the path of the selected file
            return j.getSelectedFile().getAbsolutePath();
        }

        return "";
    }
    
    public String getComputer1FileName() {
        return computer1FileName.getText();
    }
    
    public String getComputer2FileName() {
        return computer2FileName.getText();
    }

    public void click(java.awt.event.MouseEvent e)
    {
        moveStones(0);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        pits = Mancala3.sharePits();
        anotherMove = false;

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mancala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mancala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mancala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mancala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mancala().setVisible(true);
            }
        });
    }

    public void changePlayerText(String word)
    {
       turnLabel.setText(word);
    }

    public static void updatePits()
    {

        String num;
        for(int i=0; i<14; ++i)
        {
            num = String.valueOf(pits[i].numStones);
            pits[i].b.setText(num);

        }
    }
    public static boolean getHumanStatus(int p)
    {
        if(p==0){return p1Human;}
        if(p==1){return p2Human;}
        return false;
    }


    public static void getPlayerNum(int num)
    {
        System.out.println("GUI got player num" + num);
        playerNum = num;
    }

    public static void moveStones(int num)
    {

         pits = Mancala3.sharePits();
        //pits[13].b.setText("0");
            int numStones;
           numStones= pits[num].numStones;
           int i = num-1;
           while(numStones>0)
           {
               if(i<0)
               {
                i=13;
               }
               //this clause skips the appropriate goal
               if(playerNum ==0)
               {

                    if(i == 7)
                    { System.out.println("Should skip goal");
                        i=6;
                    }
               }
               if(playerNum ==1)
               {
                   if(i == 0)
                    i =13;
               }
               pits[i].numStones++;
               numStones--;
               i--;

           }
           pits[num].numStones =0;

            i+=1;
           if(pits[i].numStones == 1)
           {

               System.out.println("LANDED IN BLANK");
               if(pitAcross(i)==-1)
               {
                   System.out.println("ERROR");
                   return;

               }
               if(playerNum ==0)
               {

                   if(i>0 && i<7)
                   {
                          numToGoal=pits[pitAcross(i)].numStones+pits[i].numStones;
                          pits[pitAcross(i)].numStones =0;
                          pits[i].numStones = 0;
                          pits[0].numStones += numToGoal;
                          System.out.println("GOAL SHOULD BE"+pits[0].numStones);
                   }
               }
               if(playerNum ==1)
               {
                   if(i>7 && i<14)
                   {
                          numToGoal=pits[pitAcross(i)].numStones+pits[i].numStones;
                          pits[pitAcross(i)].numStones =0;
                          pits[i].numStones = 0;
                           pits[7].numStones += numToGoal;
                          System.out.println("GOAL SHOULD BE"+pits[7].numStones);

                   }
               }


                    updatePits();


               anotherMove = false;


           }
           if(i == 7 || i == 0)
           {
               System.out.println("LANDED IN GOAL");
               anotherMove =true;
           }
           updatePits();



    }

    public static int pitAcross(int i)
    {
        if(i ==1){return 13;}
        if(i ==2){return 12;}
        if(i ==3){return 11;}
        if(i ==4){return 10;}
        if(i ==5){return 9;}
        if(i ==6){return 8;}

        if(i ==8){return 6;}
        if(i ==9){return 5;}
        if(i ==10){return 4;}
        if(i ==11){return 3;}
        if(i ==12){return 2;}
        if(i ==13){return 1;}
        else return -1;


    }

    public static void finalScore(int p)
    {
        int sum =0;
        pits = Mancala3.sharePits();
        if(p==0)
        {
            for(int i = 1;i<7;++i)
            {
                sum += pits[i].numStones;
                pits[i].numStones =0;

            }

            pits[0].numStones += sum;

        }
        else if(p==1)
        {
                for(int i = 8;i<14;++i)
                {
                    sum += pits[i].numStones;
                    pits[i].numStones =0;

                }
                pits[7].numStones+=sum;

        }
        updatePits();



    }
    public static int numClicked()
    {
        if(clicked !=0)
            System.out.println(clicked + "was Clicked");
        return clicked;
    }
    
    public void addDebug(String message)
    {
        debugInfo.append(message + "\n");
    }

    public Player getCurrentPlayer() {
        return currentPlayer;
    }

    public void setCurrentPlayer(Player currentPlayer) {
        this.currentPlayer = currentPlayer;
        currentPlayer.setMoveMade(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computer1FileName;
    private javax.swing.JLabel computer2FileName;
    private javax.swing.JTextArea debugInfo;
    private javax.swing.JLabel errorText;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton goal1;
    private javax.swing.JButton goal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton player1ComputerButton;
    private javax.swing.JButton player1HumanButton;
    private javax.swing.JLabel player1Label;
    private javax.swing.JButton player2ComputerButton;
    private javax.swing.JButton player2HumanButton;
    private javax.swing.JLabel player2Label;
    private javax.swing.JButton resetGameButton;
    private javax.swing.JButton startGameButton;
    private javax.swing.JTextField timeLimitInput;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
